### ISSUE TITLE
Error executing tutorial Tutorial 2: 03_bss-fun-metad-analysis.ipynb

### ISSUE THREAD

**Issue by jmichel80** [OpenBioSim/BioSimSpaceTutorials#6]
Running interactively [02_bss-fun-metad-analysis.ipynb](https://github.com/OpenBioSim/BioSimSpaceTutorials/blob/main/02_funnel_metad/02_bss-fun-metad-analysis.ipynb) on Ubuntu Linux with BSS 2023.2.2 , python 3.9.16 triggers a runtime error

![image](https://github.com/OpenBioSim/BioSimSpaceTutorials/assets/11722212/dd4ec1c7-8aa5-41d9-b8d2-70978112f0a8)

Note that this tutorial requires that PLUMED is installed as a dependency (I installed it via conda-forge)

**Comment by lohedges** [comment]
Yes, it requires `plumed` for the analysis only, i.e. not actually running the metadynamics. We decided to make the OpenMM output `plumed` format so that we could use a single analysis tool. I think we should just specify this as a dependency for the tutorial, but it might be worth checking whether it causes any issues with environment resolution. If so, we could add it to the Sire host dependencies. (I've always built my own version of `plumed`.)

**Comment by jmichel80** [comment]
@lohedges is the `ValueError` seen here related to https://github.com/OpenBioSim/BioSimSpaceTutorials/issues/4 ?

**Comment by lohedges** [comment]
Yes, this is the same issue. I'll fix both at the same time. I will be wrapping the updated Sire center of mass code, so don't want to fix things twice. I'll cross reference to close the two issues when I'm done.

**Comment by lohedges** [comment]
This will be closed via the PR cross-referenced at the link above.
